#!/usr/bin/env python3
"""Generate main/digits.h from a folder of 0.png .. 9.png digit images.

Each PNG is composited over black, converted to little-endian RGB565 (what
IpstubeModule::drawBitmap expects), and emitted as a flash array. A kDigits[10]
table indexes them by digit value. Default size is one IPSTube panel (135x240).

    pip install pillow
    scripts/gen-digits.py                       # default asset dir below
    scripts/gen-digits.py /path/to/digit/pngs   # a different digit set
"""
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow not installed — run: pip install pillow")

W, H = 135, 240
DEFAULT_ASSETS = "/Users/gbryant/github/EleksTubeHAX/assets/other graphics/4 flip clock"
OUT = Path(__file__).resolve().parent.parent / "main" / "digits.h"


def to_rgb565(path):
    img = Image.open(path)
    if img.mode in ("RGBA", "LA", "PA") or (img.mode == "P" and "transparency" in img.info):
        img = img.convert("RGBA")
        img = Image.alpha_composite(Image.new("RGBA", img.size, (0, 0, 0, 255)), img)
    img = img.convert("RGB")
    if img.size != (W, H):
        img = img.resize((W, H), Image.LANCZOS)
    d = img.tobytes()  # row-major RGB
    return [((d[i] & 0xF8) << 8) | ((d[i + 1] & 0xFC) << 3) | (d[i + 2] >> 3)
            for i in range(0, len(d), 3)]


def main():
    assets = Path(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ASSETS)
    out = ["// Generated by scripts/gen-digits.py — do not edit by hand.",
           f"// Source: {assets}",
           "#pragma once", "#include <stdint.h>", ""]
    for n in range(10):
        png = assets / f"{n}.png"
        if not png.exists():
            sys.exit(f"missing {png}")
        px = to_rgb565(png)
        out.append(f"static const uint16_t digit_{n}[{W} * {H}] = {{")
        for i in range(0, len(px), 12):
            out.append("    " + ", ".join(f"0x{v:04X}" for v in px[i:i + 12]) + ",")
        out.append("};")
        out.append("")
    out.append("static const uint16_t *const kDigits[10] = {")
    out.append("    " + ", ".join(f"digit_{n}" for n in range(10)) + ",")
    out.append("};")
    out.append(f"static const int kDigitWidth  = {W};")
    out.append(f"static const int kDigitHeight = {H};")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}  (10 digits, {W}x{H}, ~{10 * W * H * 2 // 1024} KB)")


if __name__ == "__main__":
    main()
